apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-cd-nginx
  name: argo-cd-nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: argo-cd-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-cd-nginx
  name: argo-cd-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-cd-nginx
  template:
    metadata:
      labels:
        app: argo-cd-nginx
    spec:
      containers:
      - image: nginx
        name: argo-cd-nginx
        ports:
        - containerPort: 80
